apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-argo-application
  namespace: cluster-core
spec:
  project: default

  source:
    repoURL: https://github.com/enjoychange/app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-app
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
    automated:
      selfHeal: true
      prune: true

    
